# Generated by Django 4.0.4 on 2022-05-14 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('account_password', models.CharField(max_length=100)),
                ('account_started', models.DateTimeField(auto_now_add=True)),
                ('account_ended', models.DateTimeField(auto_now=True)),
                ('account_refil_count', models.IntegerField(default=0)),
                ('account_refil_date', models.DateTimeField(auto_now=True)),
                ('account_tl_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('profile_password', models.CharField(max_length=100)),
                ('profile_credit', models.IntegerField(default=0)),
                ('profile_created', models.DateTimeField(auto_now_add=True)),
                ('profile_ends', models.DateTimeField(auto_now=True)),
                ('profile_bought_for', models.IntegerField(default=30)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.account')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_profiles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='account',
            name='profiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.profile'),
        ),
    ]
