# Generated by Django 4.0.4 on 2022-05-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('account_password', models.CharField(max_length=100)),
                ('account_started', models.DateField()),
                ('account_ended', models.DateField()),
                ('account_refil_count', models.IntegerField(default=0)),
                ('account_refil_date', models.DateField(auto_now=True)),
                ('account_tl_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=100)),
                ('profile_password', models.CharField(max_length=100)),
                ('profile_credit', models.IntegerField(default=0)),
                ('profile_created', models.DateField(auto_now_add=True)),
                ('profile_ends', models.DateField(auto_now_add=True)),
                ('profile_bought_for', models.CharField(max_length=10)),
                ('profile_type', models.CharField(default='NonVPN', max_length=100)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.account')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('customer_name', 'cid'), name='customer_name_unique'),
        ),
        migrations.AddField(
            model_name='account',
            name='profiles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.profile'),
        ),
    ]
