# Generated by Django 4.0.4 on 2022-05-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_account_account_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(default='NonVPN', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_ended',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_started',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_ends',
            field=models.DateField(auto_now_add=True),
        ),
    ]
